package ast;

public enum Op {
ACCESO,INDICE,SIGNO,MOD,DIV, MUL,SUMA,RESTA,NOT,MEQ,MAQ,MENOR,MAYOR,AND,OR,
IGUAL,DISTINTO,CALL,LISTA,ARRAYINIT,BASICO_ENT,BASICO_BUL,BASICO_CAR,BASICO_ID,PUNTERO,PUNTEROINV, BASICO_NEW
}
