
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Apr 16 14:24:23 CEST 2021
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int Or = 26;
  public static final int Entero = 3;
  public static final int Bul = 9;
  public static final int Coma = 46;
  public static final int Guion = 34;
  public static final int Arr = 7;
  public static final int POR = 49;
  public static final int Indice = 38;
  public static final int If = 15;
  public static final int PCIERRE = 51;
  public static final int Id = 2;
  public static final int From = 5;
  public static final int PC = 41;
  public static final int PA = 40;
  public static final int Menor = 28;
  public static final int Else = 16;
  public static final int Maq = 31;
  public static final int Mayor = 30;
  public static final int Punto = 18;
  public static final int No = 21;
  public static final int Car = 10;
  public static final int Return = 13;
  public static final int NUM = 52;
  public static final int While = 17;
  public static final int CC = 43;
  public static final int CA = 42;
  public static final int LC = 45;
  public static final int EOF = 0;
  public static final int Asign = 23;
  public static final int LA = 44;
  public static final int Not = 32;
  public static final int Function = 12;
  public static final int And = 27;
  public static final int error = 1;
  public static final int Distinto = 24;
  public static final int Import = 4;
  public static final int DosPts = 47;
  public static final int Div = 36;
  public static final int PAP = 50;
  public static final int Acceso = 39;
  public static final int Const = 6;
  public static final int Mul = 35;
  public static final int Mod = 37;
  public static final int Data = 11;
  public static final int Si = 20;
  public static final int Caracter = 22;
  public static final int Length = 19;
  public static final int Ent = 8;
  public static final int Meq = 29;
  public static final int Suma = 33;
  public static final int Main = 14;
  public static final int Igual = 25;
  public static final int MAS = 48;
}

