
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Apr 16 13:49:26 CEST 2021
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int NUM = 6;
  public static final int PCIERRE = 5;
  public static final int MAS = 2;
  public static final int error = 1;
  public static final int PAP = 4;
  public static final int POR = 3;
  public static final int EOF = 0;
}

