
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Apr 28 11:35:35 CEST 2021
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int Or = 28;
  public static final int Entero = 3;
  public static final int Bul = 9;
  public static final int Coma = 48;
  public static final int Guion = 36;
  public static final int Arr = 7;
  public static final int Indice = 40;
  public static final int If = 16;
  public static final int Id = 2;
  public static final int From = 5;
  public static final int Backslash = 50;
  public static final int PC = 43;
  public static final int PA = 42;
  public static final int Menor = 30;
  public static final int Else = 17;
  public static final int Maq = 33;
  public static final int Mayor = 32;
  public static final int Punto = 20;
  public static final int No = 22;
  public static final int Car = 10;
  public static final int Return = 14;
  public static final int While = 18;
  public static final int CC = 45;
  public static final int CA = 44;
  public static final int For = 19;
  public static final int LC = 47;
  public static final int EOF = 0;
  public static final int Asign = 25;
  public static final int LA = 46;
  public static final int Not = 34;
  public static final int Function = 12;
  public static final int And = 29;
  public static final int error = 1;
  public static final int Distinto = 26;
  public static final int Import = 4;
  public static final int DosPts = 49;
  public static final int Div = 38;
  public static final int Acceso = 41;
  public static final int Const = 6;
  public static final int Mul = 37;
  public static final int Mod = 39;
  public static final int Data = 11;
  public static final int Si = 21;
  public static final int Caracter = 24;
  public static final int Type = 13;
  public static final int Ent = 8;
  public static final int Kut = 23;
  public static final int Suma = 35;
  public static final int Meq = 31;
  public static final int Main = 15;
  public static final int Igual = 27;
}

